name: "Danger JS"
on: [pull_request]

jobs:
    build:
        name: Danger JS
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: Use Node.js 10.x
            uses: actions/setup-node@v1
            with:
              node-version: 10.x
          - name: install yarn
            run: npm install -g yarn
          - name: yarn install
            run: yarn add danger --dev
          - name: Danger
            run: yarn danger ci
            env: 
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
